blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/craftcms/feed-me/discussions/new?category=ideas
    about: Start a new discussion about your idea
  - name: Documentation
    url: https://docs.craftcms.com/feed-me/v4/
    about: Read the official documentation
